export const CAR_BRANDS = [
    "Abarth",
    "AC",
    "Acura",
    "Aixam",
    "Alfa Romeo",
    "ALPINA",
    "Artega",
    "Asia Motors",
    "Aston Martin",
    "Audi",
    "Austin",
    "Austin Healey",
    "Bentley",
    "BMW",
    "Borgward",
    "Brilliance",
    "Bugatti",
    "Buick",
    "Cadillac",
    "Casalini",
    "Caterham",
    "Chatenet",
    "Chevrolet",
    "Chrysler",
    "CitroÃƒÆ’Ã‚Â«n",
    "Cobra",
    "Corvette",
    "Dacia",
    "Daewoo",
    "Daihatsu",
    "DeTomaso",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Fisker",
    "Ford",
    "GAC Gonow",
    "Gemballa",
    "GMC",
    "Grecav",
    "Hamann",
    "Holden",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "Iveco",
    "Jaguar",
    "Jeep",
    "Kia",
    "KÃƒÆ’Ã‚Â¶nigsegg",
    "KTM",
    "Lada",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Landwind",
    "Lexus",
    "Ligier",
    "Lincoln",
    "Lotus",
    "Mahindra",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MG",
    "Microcar",
    "MINI",
    "Mitsubishi",
    "Morgan",
    "Nissan",
    "NSU",
    "Oldsmobile",
    "Opel",
    "Pagani",
    "Peugeot",
    "Piaggio",
    "Plymouth",
    "Pontiac",
    "Porsche",
    "Proton",
    "Renault",
    "Rolls-Royce",
    "Rover",
    "Ruf",
    "Saab",
    "Santana",
    "Seat",
    "Skoda",
    "Smart",
    "speedART",
    "Spyker",
    "Ssangyong",
    "Subaru",
    "Suzuki",
    "Talbot",
    "Tata",
    "TECHART",
    "Tesla",
    "Toyota",
    "Trabant",
    "Triumph",
    "TVR",
    "Volkswagen",
    "Volvo",
    "Wartburg",
    "Westfield",
    "Wiesmann"
];

export const CAR_MODELS = [
    "500",
    "500C",
    "595",
    "595C",
    "695",
    "695C",
    "Grande Punto",
    "Punto Evo",
    "500",
    "500C",
    "595",
    "595C",
    "695",
    "695C",
    "Grande Punto",
    "Punto Evo",
    "500",
    "500C",
    "595",
    "595C",
    "695",
    "695C",
    "Grande Punto",
    "Punto Evo",
    "MDX",
    "NSX",
    "RL",
    "RSX",
    "TL",
    "TSX",
    "City",
    "Crossline",
    "Roadline",
    "Scouty R",
    "4C",
    "8C",
    "Alfa 145",
    "Alfa 146",
    "Alfa 147",
    "Alfa 155",
    "Alfa 156",
    "Alfa 159",
    "Alfa 164",
    "Alfa 166",
    "Alfa 33",
    "Alfa 75",
    "Alfa 90",
    "Alfasud",
    "Alfetta",
    "Brera",
    "Crosswagon",
    "Giulia",
    "Giulietta",
    "GT",
    "GTV",
    "Junior",
    "MiTo",
    "Spider",
    "Sprint",
    "B10",
    "B12",
    "B3",
    "B4",
    "B5",
    "B6",
    "B7",
    "B8",
    "D 10",
    "D3",
    "D5",
    "Roadster S",
    "XD3",
    "GT",
    "Rocsta",
    "AR1",
    "Cygnet",
    "DB",
    "DB7",
    "DB9",
    "DBS",
    "Lagonda",
    "Rapide",
    "V12 Vantage",
    "V8 Vantage",
    "Vanquish",
    "Virage",
    "100",
    "200",
    "80",
    "90",
    "A1",
    "A2",
    "A3",
    "A4",
    "A4 Allroad",
    "A5",
    "A6",
    "A6 Allroad",
    "A7",
    "A8",
    "Cabriolet",
    "CoupÃƒÂ©",
    "Q3",
    "Q5",
    "Q7",
    "QUATTRO",
    "R8",
    "RS2",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "RSQ3",
    "S1",
    "S2",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ5",
    "TT",
    "V8",
    "Arnage",
    "Azure",
    "Brooklands",
    "Continental",
    "Eight",
    "Flying Spur",
    "Mulsanne",
    "Turbo R",
    "Turbo RT",
    "Turbo S",
    "Series 1",
    "2002",
    "Series 2",
    "Series 3",
    "Series 4",
    "Series 5",
    "Series 6",
    "Series 7",
    "840",
    "850",
    "i3",
    "i8",
    "M Models",
    "Series X",
    "Series Z",
    "BC3",
    "BS2",
    "BS4",
    "BS6",
    "EB 110",
    "Veyron",
    "Century",
    "Electra",
    "Enclave",
    "La Crosse",
    "Le Sabre",
    "Park Avenue",
    "Regal",
    "Riviera",
    "Roadmaster",
    "Skylark",
    "Allante",
    "ATS",
    "BLS",
    "CTS",
    "Deville",
    "Eldorado",
    "Escalade",
    "Fleetwood",
    "Seville",
    "SRX",
    "STS",
    "XLR",
    "2500",
    "Alero",
    "Astro",
    "Avalanche",
    "Aveo",
    "Beretta",
    "Blazer",
    "C1500",
    "Camaro",
    "Caprice",
    "Captiva",
    "Cavalier",
    "Chevelle",
    "Chevy Van",
    "Citation",
    "Colorado",
    "Corsica",
    "Cruze",
    "El Camino",
    "Epica",
    "Evanda",
    "Express",
    "G",
    "HHR",
    "Impala",
    "K1500",
    "K30",
    "Kalos",
    "Lacetti",
    "Lumina",
    "Malibu",
    "Matiz",
    "Nubira",
    "Orlando",
    "Rezzo",
    "S-10",
    "Silverado",
    "Spark",
    "SSR",
    "Suburban",
    "Tahoe",
    "Trailblazer",
    "Trans Sport",
    "Trax",
    "Venture",
    "Volt",
    "300 M",
    "300C",
    "Aspen",
    "Crossfire",
    "Daytona",
    "ES",
    "Grand Voyager",
    "GS",
    "GTS",
    "Imperial",
    "Le Baron",
    "Neon",
    "New Yorker",
    "Pacifica",
    "PT Cruiser",
    "Saratoga",
    "Sebring",
    "Stratus",
    "Valiant",
    "Viper",
    "Vision",
    "Voyager",
    "2 CV",
    "AX",
    "Berlingo",
    "BX",
    "C-Crosser",
    "C-ElysÃƒÂ©e",
    "C-Zero",
    "C1",
    "C2",
    "C3",
    "C3 Picasso",
    "C4",
    "C4 Aircross",
    "C4 Cactus",
    "C4 Picasso",
    "C5",
    "C6",
    "C8",
    "CX",
    "DS",
    "DS3",
    "DS4",
    "DS5",
    "Evasion",
    "Grand C4 Picasso",
    "GSA",
    "Jumper",
    "Jumpy",
    "Nemo",
    "SAXO",
    "SM",
    "Visa",
    "Xantia",
    "XM",
    "Xsara",
    "Xsara Picasso",
    "ZX",
    "C1",
    "C2",
    "C3",
    "C4",
    "C5",
    "C6",
    "C7",
    "Z06",
    "ZR 1",
    "Dokker",
    "Duster",
    "Lodgy",
    "Logan",
    "Logan Pick-Up",
    "Pick Up",
    "Sandero",
    "Espero",
    "Evanda",
    "Kalos",
    "Korando",
    "Lacetti",
    "Lanos",
    "Leganza",
    "Matiz",
    "Musso",
    "Nexia",
    "Nubira",
    "Rezzo",
    "Tacuma",
    "Applause",
    "Charade",
    "Charmant",
    "Copen",
    "Cuore",
    "Feroza/Sportrak",
    "Freeclimber",
    "Gran Move",
    "Hijet",
    "MATERIA",
    "Move",
    "Rocky/Fourtrak",
    "Sirion",
    "Terios",
    "TREVIS",
    "YRV",
    "GuarÃƒ ",
    "Pantera",
    "Avenger",
    "Caliber",
    "Challenger",
    "Charger",
    "Dakota",
    "Demon",
    "Durango",
    "Grand Caravan",
    "Hornet",
    "Journey",
    "Magnum",
    "Neon",
    "Nitro",
    "RAM",
    "Stealth",
    "Viper",
    "208",
    "246",
    "250",
    "275",
    "288",
    "308",
    "328",
    "330",
    "348",
    "360",
    "365",
    "400",
    "412",
    "456",
    "458",
    "512",
    "550",
    "575",
    "599 GTB",
    "612",
    "750",
    "California",
    "Daytona",
    "Dino GT4",
    "Enzo Ferrari",
    "F12",
    "F355",
    "F40",
    "F430",
    "F50",
    "FF",
    "LaFerrari",
    "Mondial",
    "Superamerica",
    "Testarossa",
    "124",
    "126",
    "127",
    "130",
    "131",
    "500",
    "500C",
    "500L",
    "500L Living",
    "500L Trekking",
    "500X",
    "Barchetta",
    "Brava",
    "Bravo",
    "Cinquecento",
    "Coupe",
    "Croma",
    "Dino",
    "Doblo",
    "Ducato",
    "Fiorino",
    "Freemont",
    "Grande Punto",
    "Idea",
    "Linea",
    "Marea",
    "Marengo",
    "Multipla",
    "New Panda",
    "Palio",
    "Panda",
    "Punto",
    "Punto Evo",
    "Qubo",
    "Regata",
    "Ritmo",
    "Scudo",
    "Sedici",
    "Seicento",
    "Spider Europa",
    "Stilo",
    "Strada",
    "Tempra",
    "Tipo",
    "Ulysse",
    "Uno",
    "X 1/9",
    "Karma",
    "Aerostar",
    "B-Max",
    "Bronco",
    "C-Max",
    "Capri",
    "Cougar",
    "Courier",
    "Crown",
    "Econoline",
    "Econovan",
    "EcoSport",
    "Edge",
    "Escape",
    "Escort",
    "Excursion",
    "Expedition",
    "Explorer",
    "Express",
    "F 150",
    "F 250",
    "F 350",
    "Fairlane",
    "Falcon",
    "Fiesta",
    "Flex",
    "Focus",
    "Fusion",
    "Galaxy",
    "Granada",
    "Grand C-Max",
    "Grand Tourneo",
    "GT",
    "Ka",
    "Kuga",
    "Maverick",
    "Mercury",
    "Mondeo",
    "Mustang",
    "Orion",
    "Probe",
    "Puma",
    "Ranger",
    "Raptor",
    "S-Max",
    "Scorpio",
    "Sierra",
    "Sportka",
    "Streetka",
    "Taunus",
    "Taurus",
    "Thunderbird",
    "Tourneo",
    "Transit",
    "Windstar",
    "Acadia",
    "Envoy",
    "Safari",
    "Savana",
    "Sierra",
    "Sonoma",
    "Syclone",
    "Typhoon",
    "Vandura",
    "Yukon",
    "Sonique",
    "Accord",
    "Aerodeck",
    "Civic",
    "Concerto",
    "CR-V",
    "CR-Z",
    "CRX",
    "Element",
    "FR-V",
    "HR-V",
    "Insight",
    "Integra",
    "Jazz",
    "Legend",
    "Logo",
    "NSX",
    "Odyssey",
    "Prelude",
    "S2000",
    "Shuttle",
    "Stream",
    "H1",
    "H2",
    "H3",
    "Accent",
    "Atos",
    "Azera",
    "Coupe",
    "Elantra",
    "Excel",
    "Galloper",
    "Genesis",
    "Getz",
    "Grand Santa Fe",
    "Grandeur",
    "H 100",
    "H 200",
    "H-1",
    "H-1 Starex",
    "i10",
    "i20",
    "i30",
    "i40",
    "i50",
    "ix20",
    "ix35",
    "ix55",
    "Lantra",
    "Matrix",
    "Pony",
    "S-Coupe",
    "Santa Fe",
    "Santamo",
    "Sonata",
    "Terracan",
    "Trajet",
    "Tucson",
    "Veloster",
    "Veracruz",
    "XG 30",
    "XG 350",
    "EX30",
    "EX35",
    "EX37",
    "FX",
    "G35",
    "G37",
    "M30",
    "M35",
    "M37",
    "Q45",
    "Q50",
    "Q60",
    "Q70",
    "QX50",
    "QX56",
    "QX70",
    "Campo",
    "D-Max",
    "Gemini",
    "Midi",
    "PICK UP",
    "Trooper",
    "Massif",
    "Daimler",
    "E-Type",
    "F-Type",
    "MK II",
    "S-Type",
    "X-Type",
    "XE",
    "XF",
    "XJ",
    "XJ12",
    "XJ40",
    "XJ6",
    "XJ8",
    "XJR",
    "XJS",
    "XJSC",
    "XK",
    "XKR",
    "Cherokee",
    "CJ",
    "Comanche",
    "Commander",
    "Compass",
    "Grand Cherokee",
    "Patriot",
    "Renegade",
    "Wagoneer",
    "Willys",
    "Wrangler",
    "Besta",
    "Borrego",
    "Carens",
    "Carnival",
    "cee'd",
    "cee'd Sportswagon",
    "Cerato",
    "Clarus",
    "Elan",
    "Joice",
    "K2500",
    "K2700",
    "Leo",
    "Magentis",
    "Mentor",
    "Mini",
    "Opirus",
    "Optima",
    "Picanto",
    "Pregio",
    "Pride",
    "pro_cee'd",
    "Retona",
    "Rio",
    "Roadster",
    "Rocsta",
    "Sephia",
    "Shuma",
    "Sorento",
    "Soul",
    "Sportage",
    "Venga",
    "CCR",
    "X-BOW",
    "110",
    "111",
    "112",
    "1200",
    "2107",
    "2110",
    "2111",
    "2112",
    "Aleko",
    "Forma",
    "Granta",
    "Kalina",
    "Niva",
    "Nova",
    "Priora",
    "Samara",
    "Aventador",
    "Countach",
    "Diablo",
    "Espada",
    "Gallardo",
    "HuracÃƒÂ¡n",
    "Jalpa",
    "LM",
    "Miura",
    "MurciÃƒÂ©lago",
    "Urraco",
    "Beta",
    "Dedra",
    "Delta",
    "Flaminia",
    "Flavia",
    "Fulvia",
    "Gamma",
    "Kappa",
    "Lybra",
    "MUSA",
    "Phedra",
    "Prisma",
    "Stratos",
    "Thema",
    "Thesis",
    "Voyager",
    "Ypsilon",
    "Zeta",
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Serie I",
    "Serie II",
    "Serie III",
    "CV-9",
    "S",
    "SC2",
    "SC4",
    "CT 200h",
    "ES Series",
    "GS Series",
    "GX 470",
    "IS Series",
    "LS Series",
    "LX Series",
    "NX Series",
    "RC F",
    "RX Series",
    "SC 400",
    "SC 430",
    "Ambra",
    "Be Sun",
    "JS 50",
    "JS 50 L",
    "JS RC",
    "Nova",
    "Optima",
    "X - Too",
    "Aviator",
    "Continental",
    "LS",
    "Mark",
    "Navigator",
    "Town Car",
    "340 R",
    "Cortina",
    "Elan",
    "Elise",
    "Elite",
    "Esprit",
    "Europa",
    "Evora",
    "Excel",
    "Exige",
    "Super Seven",
    "222",
    "224",
    "228",
    "3200",
    "418",
    "420",
    "4200",
    "422",
    "424",
    "430",
    "Biturbo",
    "Ghibli",
    "GranCabrio",
    "Gransport",
    "Granturismo",
    "Indy",
    "Karif",
    "MC12",
    "Merak",
    "Quattroporte",
    "Shamal",
    "Spyder",
    "57",
    "62",
    "121",
    "2",
    "3",
    "323",
    "5",
    "6",
    "626",
    "929",
    "B series",
    "Bongo",
    "BT-50",
    "CX-3",
    "CX-5",
    "CX-7",
    "CX-9",
    "Demio",
    "E series",
    "Millenia",
    "MPV",
    "MX-3",
    "MX-5",
    "MX-6",
    "Premacy",
    "Protege",
    "RX-6",
    "RX-7",
    "RX-8",
    "Tribute",
    "Xedos",
    "650S CoupÃƒÂ©",
    "650S Spider",
    "MP4-12C",
    "190",
    "200",
    "220",
    "230",
    "240",
    "250",
    "260",
    "270",
    "280",
    "290",
    "300",
    "320",
    "350",
    "380",
    "400",
    "416",
    "420",
    "450",
    "500",
    "560",
    "600",
    "A-Klasse",
    "AMG GT",
    "AMG GT S",
    "B-Klasse",
    "C-Klasse",
    "CE-Klasse",
    "Citan",
    "CL-Klasse",
    "CLA-Klasse",
    "CLC-Klasse",
    "CLK-Klasse",
    "CLS-Klasse",
    "E-Klasse",
    "G-Klasse",
    "GL-Klasse",
    "GLA-Klasse",
    "GLE 450 AMG",
    "GLK-Klasse",
    "MB 100",
    "ML-Klasse",
    "R-Klasse",
    "S-Klasse",
    "SL-Klasse",
    "SLK-Klasse",
    "SLR",
    "SLS AMG",
    "Sprinter",
    "V-Klasse",
    "Vaneo",
    "Vario",
    "Viano",
    "Vito",
    "MGA",
    "MGB",
    "MGF",
    "Midget",
    "Montego",
    "TD",
    "TF",
    "ZR",
    "ZS",
    "ZT",
    "DUÃƒË†",
    "Flex",
    "M.Go",
    "M-8",
    "MC1",
    "MC2",
    "Cabrio Series",
    "Clubman Series",
    "Clubvan",
    "Countryman Series",
    "Coupe Series",
    "MINI",
    "Paceman Series",
    "Roadster Series",
    "3000 GT",
    "ASX",
    "Canter",
    "Carisma",
    "Colt",
    "Cordia",
    "Cosmos",
    "Diamante",
    "Eclipse",
    "Galant",
    "Galloper",
    "Grandis",
    "Electric Vehicle (i-MiEV)",
    "L200",
    "L300",
    "L400",
    "Lancer",
    "Mirage",
    "Montero",
    "Outlander",
    "Pajero",
    "Pajero Pinin",
    "Pick-up",
    "Plug-in Hybrid Outlander",
    "Santamo",
    "Sapporo",
    "Sigma",
    "Space Gear",
    "Space Runner",
    "Space Star",
    "Space Wagon",
    "Starion",
    "Tredia",
    "4/4",
    "Aero 8",
    "Plus 4",
    "Plus 8",
    "Roadster",
    "100 NX",
    "200 SX",
    "240 SX",
    "280 ZX",
    "300 ZX",
    "350Z",
    "370Z",
    "Almera",
    "Almera Tino",
    "Altima",
    "Armada",
    "Bluebird",
    "Cabstar",
    "Cargo",
    "Cherry",
    "Cube",
    "e-NV200",
    "Evalia",
    "Frontier",
    "GT-R",
    "Interstar",
    "Juke",
    "King Cab",
    "Kubistar",
    "Laurel",
    "Leaf",
    "Maxima",
    "Micra",
    "Murano",
    "Navara",
    "Note",
    "NP 300",
    "NV200",
    "NV400",
    "Pathfinder",
    "Patrol",
    "PickUp",
    "Pixo",
    "Prairie",
    "Primastar",
    "Primera",
    "Pulsar",
    "Qashqai",
    "Qashqai+2",
    "Quest",
    "Sentra",
    "Serena",
    "Silvia",
    "Skyline",
    "Sunny",
    "Terrano",
    "Tiida",
    "Titan",
    "Trade",
    "Urvan",
    "Vanette",
    "X-Trail",
    "Bravada",
    "Custom Cruiser",
    "Cutlass",
    "Delta 88",
    "Silhouette",
    "Supreme",
    "Toronado",
    "Adam",
    "Agila",
    "Ampera",
    "Antara",
    "Arena",
    "Ascona",
    "Astra",
    "Calibra",
    "Campo",
    "Cascada",
    "Cavalier",
    "Combo",
    "Commodore",
    "Corsa",
    "Diplomat",
    "Frontera",
    "GT",
    "Insignia",
    "Insignia CT",
    "Kadett",
    "Karl",
    "Manta",
    "Meriva",
    "Mokka",
    "Monterey",
    "Monza",
    "Movano",
    "Nova",
    "Omega",
    "Pick Up Sportscap",
    "Rekord",
    "Senator",
    "Signum",
    "Sintra",
    "Speedster",
    "Tigra",
    "Vectra",
    "Vivaro",
    "Zafira",
    "Zafira Tourer",
    "1007",
    "104",
    "106",
    "107",
    "108",
    "2008",
    "204",
    "205",
    "206",
    "207",
    "208",
    "3008",
    "301",
    "304",
    "305",
    "306",
    "307",
    "308",
    "309",
    "4007",
    "4008",
    "404",
    "405",
    "406",
    "407",
    "5008",
    "504",
    "505",
    "508",
    "604",
    "605",
    "607",
    "806",
    "807",
    "Bipper",
    "Bipper Tepee",
    "Boxer",
    "Expert",
    "Expert Tepee",
    "iOn",
    "J5",
    "Partner",
    "Partner Tepee",
    "RCZ",
    "TePee",
    "APE",
    "APE TM",
    "Porter",
    "Prowler",
    "6000",
    "Bonneville",
    "Fiero",
    "Firebird",
    "G6",
    "Grand-Am",
    "Grand-Prix",
    "GTO",
    "Montana",
    "Solstice",
    "Sunbird",
    "Sunfire",
    "Targa",
    "Trans Am",
    "Trans Sport",
    "Vibe",
    "356",
    "911",
    "912",
    "914",
    "918",
    "924",
    "928",
    "944",
    "959",
    "962",
    "968",
    "Boxster",
    "Carrera GT",
    "Cayenne",
    "Cayman",
    "Macan",
    "Panamera",
    "300 Serie",
    "400 Serie",
    "Alpine A110",
    "Alpine A310",
    "Alpine V6",
    "Avantime",
    "Captur",
    "Clio",
    "Coupe",
    "Espace",
    "Express",
    "Fluence",
    "Fuego",
    "Grand Espace",
    "Grand Modus",
    "Grand Scenic",
    "Kadjar",
    "Kangoo",
    "Koleos",
    "Laguna",
    "Latitude",
    "Mascott",
    "Master",
    "Megane",
    "Modus",
    "P 1400",
    "R 11",
    "R 14",
    "R 18",
    "R 19",
    "R 20",
    "R 21",
    "R 25",
    "R 30",
    "R 4",
    "R 5",
    "R 6",
    "R 9",
    "Rapid",
    "Safrane",
    "Scenic",
    "Spider",
    "Trafic",
    "Twingo",
    "Twizy",
    "Vel Satis",
    "Wind",
    "ZOE",
    "Corniche",
    "Flying Spur",
    "Ghost",
    "Park Ward",
    "Phantom",
    "Silver Cloud",
    "Silver Dawn",
    "Silver Seraph",
    "Silver Shadow",
    "Silver Spirit",
    "Silver Spur",
    "Wraith",
    "100",
    "111",
    "114",
    "115",
    "200",
    "213",
    "214",
    "216",
    "218",
    "220",
    "25",
    "400",
    "414",
    "416",
    "418",
    "420",
    "45",
    "600",
    "618",
    "620",
    "623",
    "75",
    "800",
    "820",
    "825",
    "827",
    "City Rover",
    "Metro",
    "Montego",
    "SD",
    "Streetwise",
    "9-3",
    "9-4X",
    "9-5",
    "9-7X",
    "90",
    "900",
    "9000",
    "96",
    "99",
    "Alhambra",
    "Altea",
    "Arosa",
    "Cordoba",
    "Exeo",
    "Ibiza",
    "Inca",
    "Leon",
    "Malaga",
    "Marbella",
    "Mii",
    "Terra",
    "Toledo",
    "105",
    "120",
    "130",
    "135",
    "Citigo",
    "Fabia",
    "Favorit",
    "Felicia",
    "Forman",
    "Octavia",
    "Pick-up",
    "Praktik",
    "Rapid",
    "Roomster",
    "Superb",
    "Yeti",
    "Crossblade",
    "ForFour",
    "ForTwo",
    "Roadster",
    "C8",
    "C8 AILERON",
    "C8 DOUBLE 12 S",
    "C8 LAVIOLETTE SWB",
    "C8 SPYDER SWB",
    "Actyon",
    "Family",
    "Korando",
    "Kyron",
    "MUSSO",
    "REXTON",
    "Rodius",
    "Tivoli",
    "B9 Tribeca",
    "Baja",
    "BRZ",
    "Forester",
    "Impreza",
    "Justy",
    "Legacy",
    "Libero",
    "OUTBACK",
    "SVX",
    "Trezia",
    "Tribeca",
    "Vivio",
    "XT",
    "XV",
    "Alto",
    "Baleno",
    "Cappuccino",
    "Carry",
    "Celerio",
    "Grand Vitara",
    "Ignis",
    "Jimny",
    "Kizashi",
    "Liana",
    "LJ",
    "SJ Samurai",
    "Splash",
    "Super-Carry",
    "Swift",
    "SX4",
    "SX4 S-Cross",
    "Vitara",
    "Wagon R+",
    "X-90",
    "Horizon",
    "Samba",
    "Indica",
    "Indigo",
    "Nano",
    "Safari",
    "Sumo",
    "Telcoline",
    "Telcosport",
    "Xenon",
    "Model 3",
    "Model S",
    "Model X",
    "Roadster",
    "4-Runner",
    "Auris",
    "Auris Touring Sports",
    "Avalon",
    "Avensis",
    "Avensis Verso",
    "Aygo",
    "Camry",
    "Carina",
    "Celica",
    "Corolla",
    "Corolla Verso",
    "Cressida",
    "Crown",
    "Dyna",
    "FCV",
    "FJ",
    "GT86",
    "Hiace",
    "Highlander",
    "Hilux",
    "IQ",
    "Land Cruiser",
    "Lite-Ace",
    "MR 2",
    "Paseo",
    "Picnic",
    "Previa",
    "Prius",
    "Prius+",
    "Proace",
    "RAV 4",
    "Sequoia",
    "Sienna",
    "Starlet",
    "Supra",
    "Tacoma",
    "Tercel",
    "Tundra",
    "Urban Cruiser",
    "Verso",
    "Verso-S",
    "Yaris",
    "601",
    "Dolomite",
    "Moss",
    "Spitfire",
    "TR3",
    "TR4",
    "TR5",
    "TR6",
    "TR7",
    "TR8",
    "Chimaera",
    "Griffith",
    "Tuscan",
    "181",
    "Amarok",
    "Beetle",
    "Bora",
    "Buggy",
    "Caddy",
    "CC",
    "Corrado",
    "Crafter",
    "Eos",
    "Fox",
    "Golf",
    "Iltis",
    "Jetta",
    "Karmann Ghia",
    "KÃƒÂ¤fer",
    "LT",
    "Lupo",
    "New Beetle",
    "Passat",
    "Phaeton",
    "Polo",
    "Routan",
    "Santana",
    "Scirocco",
    "Sharan",
    "T1",
    "T2",
    "T3",
    "T4",
    "T5",
    "T6",
    "Taro",
    "Tiguan",
    "Touareg",
    "Touran",
    "up!",
    "Vento",
    "XL1",
    "240",
    "244",
    "245",
    "262",
    "264",
    "340",
    "360",
    "440",
    "460",
    "480",
    "740",
    "744",
    "745",
    "760",
    "780",
    "850",
    "855",
    "940",
    "944",
    "945",
    "960",
    "965",
    "Amazon",
    "C30",
    "C70",
    "Polar",
    "S40",
    "S60",
    "S70",
    "S80",
    "S90",
    "V40",
    "V40 CC",
    "V50",
    "V60",
    "V70",
    "V90",
    "XC 60",
    "XC 70",
    "XC 90",
    "311",
    "353",
    "MF 25",
    "MF 28",
    "MF 3",
    "MF 30",
    "MF 35",
    "MF 4",
    "MF 5"
];

export const COLORS = [
    `AliceBlue`,
    `AntiqueWhite`,
    `Aqua`,
    `Aquamarine`,
    `Azure`,
    `Beige`,
    `Bisque`,
    `Black`,
    `BlanchedAlmond`,
    `Blue`,
    `BlueViolet`,
    `Brown`,
    `BurlyWood`,
    `CadetBlue`,
    `Chartreuse`,
    `Chocolate`,
    `Coral`,
    `CornflowerBlue`,
    `Cornsilk`,
    `Crimson`,
    `Cyan`,
    `DarkBlue`,
    `DarkCyan`,
    `DarkGoldenRod`,
    `DarkGray`,
    `DarkGrey`,
    `DarkGreen`,
    `DarkKhaki`,
    `DarkMagenta`,
    `DarkOliveGreen`,
    `Darkorange`,
    `DarkOrchid`,
    `DarkRed`,
    `DarkSalmon`,
    `DarkSeaGreen`,
    `DarkSlateBlue`,
    `DarkSlateGray`,
    `DarkSlateGrey`,
    `DarkTurquoise`,
    `DarkViolet`,
    `DeepPink`,
    `DeepSkyBlue`,
    `DimGray`,
    `DimGrey`,
    `DodgerBlue`,
    `FireBrick`,
    `FloralWhite`,
    `ForestGreen`,
    `Fuchsia`,
    `Gainsboro`,
    `GhostWhite`,
    `Gold`,
    `GoldenRod`,
    `Gray`,
    `Grey`,
    `Green`,
    `GreenYellow`,
    `HoneyDew`,
    `HotPink`,
    `IndianRed`,
    `Indigo`,
    `Ivory`,
    `Khaki`,
    `Lavender`,
    `LavenderBlush`,
    `LawnGreen`,
    `LemonChiffon`,
    `LightBlue`,
    `LightCoral`,
    `LightCyan`,
    `LightGoldenRodYellow`,
    `LightGray`,
    `LightGrey`,
    `LightGreen`,
    `LightPink`,
    `LightSalmon`,
    `LightSeaGreen`,
    `LightSkyBlue`,
    `LightSlateGray`,
    `LightSlateGrey`,
    `LightSteelBlue`,
    `LightYellow`,
    `Lime`,
    `LimeGreen`,
    `Linen`,
    `Magenta`,
    `Maroon`,
    `MediumAquaMarine`,
    `MediumBlue`,
    `MediumOrchid`,
    `MediumPurple`,
    `MediumSeaGreen`,
    `MediumSlateBlue`,
    `MediumSpringGreen`,
    `MediumTurquoise`,
    `MediumVioletRed`,
    `MidnightBlue`,
    `MintCream`,
    `MistyRose`,
    `Moccasin`,
    `NavajoWhite`,
    `Navy`,
    `OldLace`,
    `Olive`,
    `OliveDrab`,
    `Orange`,
    `OrangeRed`,
    `Orchid`,
    `PaleGoldenRod`,
    `PaleGreen`,
    `PaleTurquoise`,
    `PaleVioletRed`,
    `PapayaWhip`,
    `PeachPuff`,
    `Peru`,
    `Pink`,
    `Plum`,
    `PowderBlue`,
    `Purple`,
    `Red`,
    `RosyBrown`,
    `RoyalBlue`,
    `SaddleBrown`,
    `Salmon`,
    `SandyBrown`,
    `SeaGreen`,
    `SeaShell`,
    `Sienna`,
    `Silver`,
    `SkyBlue`,
    `SlateBlue`,
    `SlateGray`,
    `SlateGrey`,
    `Snow`,
    `SpringGreen`,
    `SteelBlue`,
    `Tan`,
    `Teal`,
    `Thistle`,
    `Tomato`,
    `Turquoise`,
    `Violet`,
    `Wheat`,
    `White`,
    `WhiteSmoke`,
    `Yellow`,
    `YellowGreen`,
  ]